import type { Work } from "./types";
import { WORK_IMAGE_WHITE_FALLBACK } from "./placeholders";

export const work05: Work = {
  id: "5",
  title: "Wisdom Horse",
  image: WORK_IMAGE_WHITE_FALLBACK,
  cardImageAspectRatio: 1,
  cardImageHeightPx: 581,
  overlayIcon: "./works/wisdomhorse/wisdomhorse-icon.svg",
  tags: ["网页"],
  tagsEn: ["Webpage"],
  date: "2024/04/01",
  cardIntro: "智伯乐全系列产品品牌视觉、官网、模型站与 AI 学术助手界面",
  cardIntroEn: "Branding, official site, model hub, and AI academic assistant interfaces.",
  detailTitle: "Wisdom Horse 智伯乐全系列产品品牌视觉、官网、模型站与 AI 学术助手界面",
  detailTitleEn: "Wisdom Horse Product Family Branding, Website, Model Hub, and AI Academic Assistant UI",
  typeLabel: "官网 / AI 助手 / 云服务 / 模型站",
  typeLabelEn: "Official Site / AI Assistant / Cloud / Model Hub",
  details: [
    { label: "类别", value: "官网 / AI 助手 / 云服务 / 模型站" },
    { label: "时间", value: "2024.04 - 2024.12" },
    { label: "关键词", value: "品牌升级、3D 视觉设计、组件库维护、官网更新" },
    { label: "角色", value: "UI 设计师（实习）" },
  ],
  detailsEn: [
    { label: "Category", value: "Official Site / AI Assistant / Cloud / Model Hub" },
    { label: "Timeline", value: "2024.04 - 2024.12" },
    { label: "Keywords", value: "Brand Upgrade, 3D Visuals, Component Library, Website Refresh" },
    { label: "Role", value: "UI Designer (Intern)" },
  ],
  overview:
    "负责智伯乐全系列产品的品牌视觉定义与界面优化。主导了色彩方案、图标系统及 3D 视觉营销材料的制作、绘制高保真原型并完善公司组件库，确保了品牌调性在官网、社区及 AI 学术助手等多个终端的高标准落地。",
  overviewEn:
    "Led branding and interface optimization across the Wisdom Horse product family, including color strategy, icon system, 3D marketing assets, high-fidelity prototyping, and component library maintenance for consistent multi-platform delivery.",
  layout: "half",
  cardCover: {
    background: {
      type: "reactbits",
      effect: "darkVeil",
      params: {
        hueShift: 0,
        noiseIntensity: 0,
        scanlineIntensity: 0,
        speed: 3,
        scanlineFrequency: 0.5,
        warpAmount: 0,
        resolutionScale: 1,
        offsetY: 0.08,
        scale: 1.18,
      },
      fallbackColor: "#050505",
    },
    foreground: {
      type: "stack",
      placement: { mode: "centerRatio", widthRatio: 0.4 },
      gapPx: 32,
      scaleWithPlacement: { baseWidthRatio: 0.5 },
      items: [
        { type: "image", src: "./works/wisdomhorse/wisdom_up.svg", widthRatio: 1, preserveAspectRatio: true },
        { type: "text", text: "Wisdom Horse", fontSizePx: 32, fontWeight: 500, color: "#FFFFFF" },
      ],
    },
  },
  detailImages: [
    "./works/wisdomhorse/02-03.webp",
    "./works/wisdomhorse/02-04.webp",
    "./works/wisdomhorse/02-05.webp",
    "./works/wisdomhorse/02-06.webp",
    "./works/wisdomhorse/03-02.webp",
    "./works/wisdomhorse/03-03.webp",
    "./works/wisdomhorse/03-04.webp",
    "./works/wisdomhorse/03-05.webp",
    "./works/wisdomhorse/03-06.webp",
    "./works/wisdomhorse/04-02.webp",
    "./works/wisdomhorse/04-03.webp",
    "./works/wisdomhorse/04-04.webp",
    "./works/wisdomhorse/04-05.webp",
    "./works/wisdomhorse/04-06.webp",
    "./works/wisdomhorse/05-02.webp",
    "./works/wisdomhorse/05-03.webp",
    "./works/wisdomhorse/05-04.webp",
    "./works/wisdomhorse/05-05.webp",
    "./works/wisdomhorse/05-06.webp",
    "./works/wisdomhorse/05-07.webp",
  ],
};
