import type { Work } from "./types";

export const work05: Work = {
  id: "5",
  title: "Wisdom Horse",
  image: "./works/bg/苏崇铭7.webp",
  cardImageAspectRatio: 1,
  cardImageHeightPx: 581,
  overlayIcon: "./works/wisdomhorse/wisdomhorse-icon.svg",
  tags: ["网页"],
  tagsEn: ["Webpage"],
  date: "2025/01/01",
  cardIntro: "图文叙事排版实验，强调留白与阅读流。",
  cardIntroEn: "Image-text narrative layout study focused on whitespace and reading flow.",
  typeLabel: "作品五 / 网页",
  typeLabelEn: "Work 05 / Webpage",
  details: [
    { label: "作品类型", value: "图文叙事页面" },
    { label: "时间", value: "2025/01" },
    { label: "关键词", value: "图文比例、段落节奏、滚动体验" },
    { label: "关注点", value: "轻量、顺滑、可读" },
  ],
  detailsEn: [
    { label: "Type", value: "Image-and-Text Narrative Page" },
    { label: "Time", value: "2025/01" },
    { label: "Keywords", value: "Image/Text Proportion, Paragraph Rhythm, Scrolling Experience" },
    { label: "Focus", value: "Lightweight, Smooth, Readable" },
  ],
  overview:
    "一次偏叙事的排版实验：让图片承载情绪、文字承载信息，通过留白与对齐关系引导视线；滚动过程保持克制和顺滑。",
  overviewEn:
    "A narrative-leaning typography experiment: let images carry emotion while text carries information. Guide the eye through whitespace and alignment; keep the scroll process restrained and smooth.",
  layout: "half",
  cardCover: {
    background: {
      type: "reactbits",
      effect: "darkVeil",
      params: {
        hueShift: 0,
        noiseIntensity: 0,
        scanlineIntensity: 0,
        speed: 3,
        scanlineFrequency: 0.5,
        warpAmount: 0,
        resolutionScale: 1,
        offsetY: 0.08,
        scale: 1.18,
      },
      fallbackColor: "#050505",
    },
    foreground: {
      type: "stack",
      placement: { mode: "centerRatio", widthRatio: 0.4 },
      gapPx: 32,
      scaleWithPlacement: { baseWidthRatio: 0.5 },
      items: [
        { type: "image", src: "./works/wisdomhorse/wisdom_up.svg", widthRatio: 1, preserveAspectRatio: true },
        { type: "text", text: "Wisdom Horse", fontSizePx: 32, fontWeight: 500, color: "#FFFFFF" },
      ],
    },
  },
  detailImages: [
    "./works/wisdomhorse/02-03.webp",
    "./works/wisdomhorse/02-04.webp",
    "./works/wisdomhorse/02-05.webp",
    "./works/wisdomhorse/02-06.webp",
    "./works/wisdomhorse/03-02.webp",
    "./works/wisdomhorse/03-03.webp",
    "./works/wisdomhorse/03-04.webp",
    "./works/wisdomhorse/03-05.webp",
    "./works/wisdomhorse/03-06.webp",
    "./works/wisdomhorse/04-02.webp",
    "./works/wisdomhorse/04-03.webp",
    "./works/wisdomhorse/04-04.webp",
    "./works/wisdomhorse/04-05.webp",
    "./works/wisdomhorse/04-06.webp",
    "./works/wisdomhorse/05-02.webp",
    "./works/wisdomhorse/05-03.webp",
    "./works/wisdomhorse/05-04.webp",
    "./works/wisdomhorse/05-05.webp",
    "./works/wisdomhorse/05-06.webp",
    "./works/wisdomhorse/05-07.webp",
  ],
};
