import type { Work } from "./types";

export const work05: Work = {
  id: "5",
  title: "Wisdom Horse",
  image: "./works/bg/苏崇铭7.webp",
  overlayIcon: "./works/wisdomhorse/wisdomhorse-icon.svg",
  tags: ["网页"],
  date: "2025/01/01",
  typeLabel: "作品五 / 网页",
  details: [
    { label: "作品类型", value: "图文叙事页面" },
    { label: "时间", value: "2025/01" },
    { label: "关键词", value: "图文比例、段落节奏、滚动体验" },
    { label: "关注点", value: "轻量、顺滑、可读" },
  ],
  overview:
    "一次偏叙事的排版实验：让图片承载情绪、文字承载信息，通过留白与对齐关系引导视线；滚动过程保持克制和顺滑。",
  layout: "half",
  detailImages: [
    "./works/wisdomhorse/02-03.webp",
    "./works/wisdomhorse/02-04.webp",
    "./works/wisdomhorse/02-05.webp",
    "./works/wisdomhorse/02-06.webp",
    "./works/wisdomhorse/03-02.webp",
    "./works/wisdomhorse/03-03.webp",
    "./works/wisdomhorse/03-04.webp",
    "./works/wisdomhorse/03-05.webp",
    "./works/wisdomhorse/03-06.webp",
    "./works/wisdomhorse/04-02.webp",
    "./works/wisdomhorse/04-03.webp",
    "./works/wisdomhorse/04-04.webp",
    "./works/wisdomhorse/04-05.webp",
    "./works/wisdomhorse/04-06.webp",
    "./works/wisdomhorse/05-02.webp",
    "./works/wisdomhorse/05-03.webp",
    "./works/wisdomhorse/05-04.webp",
    "./works/wisdomhorse/05-05.webp",
    "./works/wisdomhorse/05-06.webp",
    "./works/wisdomhorse/05-07.webp",
  ],
};
