import type { Work } from "./types";

export const work00Tenet: Work = {
  id: "0",
  title: "TENET",
  // Tenet 卡片不展示背景图（用纯色封面渲染），但 Work.image 目前为必填字段，这里给一个可用兜底
  image: "./works/tenet/01.webp",
  cardImageAspectRatio: 1,
  tags: ["产品"],
  tagsEn: ["Product"],
  date: "2025/07/01",
  cardIntro: "从 0 到 1 构建企业级 RAG 知识库问答系统",
  cardIntroEn: "Built an enterprise RAG knowledge-base QA system from 0 to 1.",
  detailTitle: "TENET 企业级 RAG 知识库问答系统",
  detailTitleEn: "TENET Enterprise RAG Knowledge Base QA System",
  typeLabel: "AI 业务 / B端复杂系统",
  typeLabelEn: "AI Business / Complex B2B System",
  details: [
    { label: "类别", value: "AI 业务 / B端复杂系统" },
    { label: "时间", value: "2025.07 - 2026.01" },
    { label: "关键词", value: "RAG知识库、Agent能力评估、自动化测试、全链路设计" },
    { label: "角色", value: "UI/UX 设计工程师" },
  ],
  detailsEn: [
    { label: "Category", value: "AI Business / Complex B2B System" },
    { label: "Timeline", value: "2025.07 - 2026.01" },
    { label: "Keywords", value: "RAG, Agent Evaluation, Automation Testing, End-to-End Design" },
    { label: "Role", value: "UI/UX Design Engineer" },
  ],
  overview:
    "TENET 是一款基于企业级 RAG 技术的知识库问答系统。参与该项目涵盖了从 0 到 1 的产品定位、设计规范及高复用性组件库搭建。除核心问答流程外，还深度参与了测试端支撑系统优化的设计，包括「测试数据生成系统」与「Agent 能力评估系统」，通过可视化手段将复杂的 AI 逻辑转化为易用的工具界面，赋能 AI 研发的提效与质控。",
  overviewEn:
    "TENET is an enterprise-grade RAG knowledge-base QA system. I worked on product positioning, design standards, and a highly reusable component system from 0 to 1, and also designed support systems for test-data generation and Agent capability evaluation to turn complex AI workflows into usable interfaces.",
  layout: "half",
  cardCover: {
    background: { type: "color", color: "#000000" },
    foreground: {
      type: "video",
      src: "./works/tenet/tenet.webm",
      placement: { mode: "centerRatio", widthRatio: 0.55 },
      playbackRate: 1.2,
      autoPlay: true,
      muted: true,
      loop: true,
      playsInline: true,
      controls: false,
      preload: "metadata",
    },
  },
  detailMedia: [
    { type: "image", src: "./works/tenet/01.webp" },
    { type: "video", src: "./works/tenet/guide.webm" },
    { type: "image", src: "./works/tenet/03.webp" },
    { type: "image", src: "./works/tenet/04.webp" },
    { type: "video", src: "./works/tenet/create_space.webm" },
    { type: "image", src: "./works/tenet/05.webp" },
    { type: "video", src: "./works/tenet/dialogue.webm" },
    { type: "image", src: "./works/tenet/06.webp" },
    { type: "image", src: "./works/tenet/07.webp" },
    { type: "image", src: "./works/tenet/08.webp" },
    { type: "video", src: "./works/tenet/knowledge.webm" },
    {
      type: "imageTwoUpThenOne",
      topLeftSrc: "./works/tenet/9-1.webp",
      topRightSrc: "./works/tenet/9-2.webp",
      bottomSrc: "./works/tenet/9-3.webp",
      gapPx: 16,
    },
    { type: "image", src: "./works/tenet/10.webp" },
    { type: "image", src: "./works/tenet/11.webp" },
  ],
};
